services:
    server:
      build:
        context: ./server/
        dockerfile: Dockerfile
      ports:
        - "8080:8080/udp"
      networks:
        game_net:
          ipv4_address: 172.25.0.10
      cap_add:
        - NET_ADMIN
      entrypoint: ["/entrypoint.sh"]
      volumes:
        - ./server/entrypoint.sh:/entrypoint.sh
      stdin_open: true
      tty: true
      
    client1:
      build:
        context: ./client/
        dockerfile: Dockerfile
      depends_on:
        - server
      networks:
        game_net:
          ipv4_address: 172.25.0.11
      command: >
        bash -c './client Player_$$(hostname)'
      cap_add:
        - NET_ADMIN
      entrypoint: ["/entrypoint.sh"]
      volumes:
        - ./client/entrypoint.sh:/entrypoint.sh

    client2:
      build:
        context: ./client/
        dockerfile: Dockerfile
      depends_on:
        - server
      networks:
        game_net:
          ipv4_address: 172.25.0.12
      command: >
        bash -c './client Player_$$(hostname)'
      cap_add:
        - NET_ADMIN
      entrypoint: ["/entrypoint.sh"]
      volumes:
        - ./client/entrypoint.sh:/entrypoint.sh

    client3:
      build:
        context: ./client/
        dockerfile: Dockerfile
      depends_on:
        - server
      networks:
        game_net:
          ipv4_address: 172.25.0.13
      command: >
        bash -c './client Player_$$(hostname)'
      cap_add:
        - NET_ADMIN
      entrypoint: ["/entrypoint.sh"]
      volumes:
        - ./client/entrypoint.sh:/entrypoint.sh

    client4:
      build:
        context: ./client/
        dockerfile: Dockerfile
      depends_on:
        - server
      networks:
        game_net:
          ipv4_address: 172.25.0.14
      command: >
        bash -c './client Player_$$(hostname)'
      cap_add:
        - NET_ADMIN
      entrypoint: ["/entrypoint.sh"]
      volumes:
        - ./client/entrypoint.sh:/entrypoint.sh
    
networks:
    game_net:
        driver: bridge
        ipam:
          config:
            - subnet: 172.25.0.0/24 # ¯\_(ツ)_/¯
